# https://pre-commit.com/hooks.html

# pre-commit run --all-files --verbose
# SKIP=no-commit-to-branch pre-commit run --all-files --verbose

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.3
    hooks:
      - id: isort
